chore: update to next 15, update husky, refactor: change to id for modal and drawer

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,31 +1,18 @@
-echo 'Styling, testing and building your project before committing'
+if ! git diff --cached --name-only | grep -q "CHANGELOG.md"; then
+  echo "Error: You must update CHANGELOG.md before committing."
+  exit 1
+fi
 
-# Check Prettier standards
-npm run check-format ||
-(
-    echo 'Your styling looks disgusting. Prettier Check Failed. Run npm run format, add changes using git add and try commit again.';
-    false;
+if git diff --cached --numstat | awk '{ if ($1 > 5000) { print $2 } }' | grep -q .; then
+  echo "Error: You are trying to commit a large file."
+  exit 1
+fi
+
+pnpm run check-format || (
+  echo "Please run \`pnpm run format\`"
+  exit 1
 )
 
-# Check ESLint Standards
-npm run check-lint ||
-(
-        echo 'Get that weak shit out of here! ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
-        false; 
-)
-
-npm run check-types ||
-(
-    echo 'Failed Type check. Are you seriously trying to write that? Make the changes required above.'
-    false;
-)
-
-echo 'Code looks good to me... Trying to build now. '
-
-npm run build ||
-(
-    echo '❌Your build failed ❌'
-    false;
-)
-
-echo '✅✅✅✅ I am committing this now. ✅✅✅✅'
+echo ""
+echo "Running check build"
+pnpm run build
